name: ui_test_cengizhanparlak
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.2
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_riverpod: ^2.3.6
  go_router: ^9.0.3
  google_fonts: ^5.1.0
  http: ^1.0.0
  mocktail: ^0.3.0
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.5

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.3
  shine_linters:
    git:
      url: https://github.com/CengizhanParlak/shine_linters
      ref: main

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - resources/langs/
