name: ui_test_cengizhanparlak
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  hive: ^2.2.3
  google_fonts: ^5.1.0
  infinite_scroll_pagination: ^3.2.0
  http: ^1.0.0
  riverpod_annotation: ^2.1.1
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  bot_toast: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - resources/langs/
